<?php
$bilgiAdi = array(
    1 => "Iş Adresi",
    2 => "Ev Adresi",
    3 => "İş Tel",
    4 => "Cep Tel",
    5 => "Ev Tel",
    6 => "Faks",
    7 => "Son Okul",
    8 => "Dip Türü",
    9 => "Resim"
    );
$bilgiLen = array(
    1 => "5:40",
    2 => "5:40",
    3 => "1:20",
    4 => "1:20",
    5 => "1:20",
    6 => "1:20",
    7 => "1:30",
    8 => "1:20",
    9 => "1:20"
    );
// $bilgiLen[1] -> 5:40 olur
// $bilgiAdi[1] -> is adresi olur
?>
