<?php
/* site bilgisi */
$site_adi="ROTARY CLUB";
$site_adina="ROTARY CLUB'a";

/* uygulama bilgisi */
$yakin_arkadas="1";
$mesajno      ="2";

/* resimler */
$defaultpic="resimler/bosresim.jpg";
$resimdir="resimler/";
$resimno="9";

/* dosya yollari */
$haberdir="haberler";
$reklamdir="reklamlar";

/* standart haber dosyasi */
$standart_haber="default.html";

$dbhost="localhost";
$dbname="rotary";
$dbuser="ergun";
$dbpasswd="canalan";
$webhost="http://localhost/~ergun/rotary/";
$userphp="sifreli.php";
$webuser="admin";
$webpwd="aARX4.Bbm2tXg";
?>
