    <div id="haber">
         <span class="dugme" id='d0'>
               Açık Kaynak Haberleri
         </span>
         <span class="dugme" id='d1'>
               <a href="javascript:goster('sec1','d1')">1</a>
         </span>
         <span class="dugme" id='d2'>
               <a href="javascript:goster('sec2','d2')">2</a>
         </span>
         <span class="dugme" id='d3'>
               <a href="javascript:goster('sec3','d3')">3</a>
         </span>
         <span class="dugme" id='d4'>
               <a href="javascript:goster('sec4','d4')">4</a>
         </span>
         <span class="dugme" id='d5'>
               <a href="javascript:goster('sec5','d5')">5</a>
         </span>
    </div>
    <div id="haberdetay">
         <div id="sec1" style="display: none">
<h3>OrangeHRM: Sürüm 2.3 çıktı<br />
2008-06-10 11:18 - OrangeHRM - İnsan Kaynakları Yönetimi</h3>
OrangeHRM Inc tarafından geliştirilen OrangeHRM, Açık Kaynak HR Bilgi Sistemidir (HRIS). Kişisel Bilgi Yönetimi, Çalışanın kişisel hizmeti, ayrılış, zaman ve başlama ve yaraları içerir. İş alma ve verimlilik geliştirilmektedir.
<br /><br /> 
OrangeHRM, tüm Dünyada küçük ve orta büyüklükteki girişimlerde açık kaynak HR Yönetim çözümü önderidir.
<br /><br /> 
Bu uygulamanın özellikleri şunları içerir
<br /><br /> 
Sağlık Koruma Planı (HSP)
<ol> 
<li> Tanımlama:
 
Sağlık Koruma Planında altı değişik seçenek sunulur: HSA,HRA,FSA,HSA+HRA,HSA+FSA,HRA+FSA.</li>
 
<li> Çalışanın HSP Özeti:
 
Belirli bir çalışanın onun HSP bilgilerine bakmaksızın tüm kayıtlarını listeler.
Bu liste yıllık sınırı, işveren ve çaşılanın ilişkisini ve HSP'nin o anki değerini de içerir.</li>
 
<li> HSP Ödemeleri:
 
Çalışanlar için HSP ödemelerini HR yöneticisi girip görebilir.</li>
 
<li> HSP Giderleri:
 
Bir ücretli için ödenmiş ve ödenecek HSP'leri görüntüler. Bu liste kurumun HSP sistemi hakkında açık durum belirtir.</li>
 
<li> HSP Başvurusu: 
 
Bu istek formunu çalışanlar kullanarak belirli bir yılda başlayarak sisteme giriş yaparlar. Bu form içinde bazı alanlar kapalıdır ve yöneticinin girişine açıktır.</li>
</ol> 
OrangeHRM son sürümü GNU GPL açık kaynak lisansıyla ücretsiz dağıtılır. Kaynak kod <a href="http://www.orangehrm.com">
http://www.orangehrm.com</a> adresinden sağlanabilir.
<br /><br />
         </div>
         <div id="sec2" style="display: none">
<h3>Liferea: 1.4.16 (durağan, hata ayıklama)<br />
Gönderen: llando<br />
Date: 2008-06-10 11:18</h3>
<b>Özet: Liferea: 1.4.16 (ağan, hata ayıklama)</b><br /><br />
OrangeHRM Inc tarafından geliştirilen OrangeHRM, Açık Kaynak HR Bilgi Sistemidir (HRIS). Kişisel Bilgi Yönetimi, Çalışanın kişisel hizmeti, ayrılış, zaman ve başlama ve yaraları içerir. İş alma ve verimlilik geliştirilmektedir.
<br /><br /> 
 
Bu hata ayıklama sürümüdür. Bu sürüm 1.4.1.15 sürümüyle VT tablo tanımlarındaki uyumsuzluklar için ön bellek çevirimi kullanır.
<br /><br />
         </div>
         <div id="sec3" style="display: none">
<h3>Bouml: 4.3.5 MacOS X PPC için hazırdır<br />
Gönderen: bruno_pages<br />
Tarih: 2008-06-10 11:17</h3>
<b>Özet: Bouml: MacOS X PPC için 4.3.5 sürümü</b><br />

BOULM ücretsiz araç kutusudur. C++, Java, Idl, Php ve Python kodları geliştirme ve tanımlamaya yarar. BOUML Unix/Linux/Solaris, MacOS X ve Windows altında çalışır. Çok hızlıdır ve birkaç bin sınıf bilgisi için çok bellek gerektirmez.
<br /><br /> 
Uyarı : yeni kurulum işlemleri için 
<a href="http://bouml.sourceforge.net/readme_macosx_new.txt">
http://bouml.sourceforge.net/readme_macosx_new.txt  </a>
adresine bakın.
<br /><br />
         </div>
         <div id="sec4" style="display: none">
<h3>Visual Studio 2008-05CTP için Neumont ORM Mimarisi çıktı!<br />
Gönderen: mcurland<br />
Tarih: 2008-06-10 11:18</h3>
<b>Özet: Visual Studio 2008-05CTP için Neumont ORM Mimarisi çıktı!</b><br /><br />

Nesnel Rol Modellemesi (ORM) standart sürümü 2, ilgili çizelgeler, geliştirme araçları ve Visual Studio için Neumont ORM Mimarisi biçiminde uyarlanmıştır.
 <br /><br />
 
Mayıs 2008 Komite Teknik ön incelemesi
<a href="http://www.sourceforge.net/projects/orm">
http://www.sourceforge.net/projects/orm</a> ya da 
<a href="http://www.ormfoundation.org">
http://www.ormfoundation.org></a> adreslerinde kullanıma açılmıştır.
<br /><br />
         </div>
         <div id="sec5" style="display: none">
<h3>mia-chat: Mia Chat 0.8.3 çıktı<br />
Gönderen: ozgurcemsen<br />
Tarih: 2008-06-09 15:11</h3>
<b>Özet: mia-chat: Mia Chat 0.8.3 çıktı</b>
<br /><br />
Web tabanlı Ajax char uygulamasıdır javascript ve PHP ile geliştirilmiştir. Anahtar özellikleri; Kolay kurulum, kolay kullanım, güvenlidir.
Ortam ve veri tabanından bağımsızdır.
<br /><br /> 
MiaChat
HTMLPurifier 3.1.0 kullanabilecek biçimde geliştirilmiştir.
<br /><br /> 
Yardım ve bilgi için 
<a href="http://forum.brilaps.com">
http://forum.brilaps.com</a> adresine bakın.
<br /><br />
         </div>
    </div>
