       <table cellpadding="0" cellspacing="0" width="514">
       <tr><td valign="top">
                <div id="kutu">
<br />
<br />
<a href="durgun.html">Durağan web sayfası</a><br />örnek tasarımları:<br />
10 YTL'den<br /> başlayan fiyatlarla...
                </div>
            </td>
            <td valign="top">
                <div id="kutu">
<br />
PHP, .NET, Flash gibi araçlarla<br /><a href="server.html">sunucu yazılımı</a> tasarımı ve kodlaması.<br />Proje bedeli ve iş teslimi üzerinden anlaşılır.
                </div>
            </td>
            <td valign="top">
                <div id="kutu">
<br />
<br />
(Boş) 
                </div>
            </td></tr>
       <tr><td valign="top">
                <div id="kutu">
<br />
Internet TV <br /><a href="danis.html">konusunda danışmanlık</a><br />75 YTL<br />saat ücretinden başlayan fiyatlarla
                </div>
            </td>
            <td valign="top">
                <div id="kutu">
<br />
<br />
<a href="veri.html">Bağımsız veri değişim</a><br />ve paylaşım sistemi<br />
(VPN ve Web kullanımı)
                </div>
            </td>
            <td valign="top">
                <div id="kutu">
<a href="ozel.html">Özel Proje hizmeti</a><br />Hizmet bedeli, çalışan kadronun niteliklerine göre değişen saat ücretleriyle imzalanacak sözleşmede tanımlanan süre için geçerlidir.
                </div>
            </td></tr>
       <tr><td valign="top">
                <div id="kutu">
Bilgisayar donanım ve yazılım alımlarında en uygun maliyeti belirleme ve olurluk raporları hazırlama işlemi. Rapor süresine göre hizmet bedeli belirlenir. <a href="ayrinti.html">Ayrıntılar</a>
                </div>
            </td>
            <td valign="top">
                <div id="kutu">
<a href="otomatik.html">Otomatik web sayfası</a> hazırlama yazılımı. Bu konuda ücretsiz yazılıma verilecek hizmetin saat ücreti talep edilir. İşlem süresi istenenlere bağımlıdır.
                </div>
            </td>
            <td valign="top">
                <div id="kutu">
<br />
Sürekli Yayın <br /><a href="surekli.html">konusunda danışmanlık</a><br />75 YTL<br />saat ücretinden başlayan fiyatlarla
                </div>
            </td></tr>
       </table>
