       <div class="borderright">
<b>Aybim Üyelik Sistemi</b> yalnız üyeler için sağlanan yazılım ve tasarım olanakları paylaşım ortamıdır. Üyeler kendi kaynak kodlarını paylaşıma açabildikleri gibi var olan tasarım ve kodları indirip kullanabilirler. Ayrıca üyeler kendi yazılımlarının pazarlanmasını da isteyebilirler. Ayrıntılar için <a href="uyelik.html">Üyelik Sistemi</a> sayfasına gidebilirsiniz.<br />
         <br />
         <form>
           <div id="sifre" class="yazi">
            <table class="yazi">
               <tr><th colspan="2"><center>ÜYE GİRİŞİ</center></th></tr>
              <tr><td valign="top">Üye Kodu</td>
                  <td valign="top"><input type="text" name="user" size="8" class="required"></td></tr>
              <tr><td valign="top">Şifre</td>
                      <td valign="top"><input type="text" name="passwd" size="8" class="required">
                    <input type="button" onclick="javascirpt:" value="Git"></td></tr>
            </table>
           </div>
         </form>
         <br />
         Eğer üye değilseniz ve üye olmak isterseniz <a href="uyegir.php">YENİ ÜYE GİRİŞİ</a> ile üyemiz olun. Üyelerimizle bilgilerinizi paylaşın. <b>Bilgi paylaşıldıkça değerlidir</b>.</br />
       </div>
