  <div id="soltaraf">
    <div id="masterdiv">
        <div class="menutitle" onclick="SwitchMenu('sub1')">Olanaklar</div>
        <span class="submenu" id="sub1">
                - <a href="">Bağımsız Veri Değişimi</a><br>
                - <a href="">Internet TV</a><br>
                - <a href="">WEB tasarımı</a><br>
                - <a href="">Sunucu Kurulumu</a><br>
                - <a href="">Donanım Seçenekleri</a>
        </span>
        <div class="menutitle" onclick="SwitchMenu('sub2')">Çeşitli Belgeler</div>
        <span class="submenu" id="sub2">
                - <a href="">Kullanıcılar</a><br>
                - <a href="">Blog Kurulumu</a><br>
                - <a href="">Filmler Uzantılar</a><br>
                - <a href="">Internet TV</a>
        </span>
        <div class="menutitle"><a href="" class="vnav">Hakkımızda</a></div>
        <div class="menutitle"><a href="" class="vnav">Adres</a></div>
    </div>
  </div>
