    <table cellpadding="0" cellspacing="0" border="0" width="960">
    <tr><td valign="top">
      <img src="img/bos.gif" width="15" height="63" border="0">
      <img src="img/aybim.png" width="129" height="43" border="0">
<br>
      <img src="img/bos.gif" width="15" height="1" border="0">
      <span class="yazi">Aybim Bilgisayar Tic. Ltd.</span><br>
      <img src="img/bos.gif" width="150" height="50" border="0">
      </td><td valign="top">
      </td></tr>
    </table>
