<html>
<head>
<meta content="text/html; charset=utf-8" http-equiv="content-type">
<title>VERI DEGISIMI</title>
<link rel="stylesheet" href="mainx.css" type="text/css">
<script type="text/javascript" src="js/baslik.js"></script>
<script type="text/javascript" src="js/goster.js"></script>
<script type="text/javascript" src="js/sifreli.js"></script>
<script type="text/javascript" src="js/jsmenu.js"></script>
