    <div id="haber">
         <span class="dugme" id='d0'>
               Veri Değişim Çeşitleri
         </span>
         <span class="dugme" id='d1'>
               <a href="javascript:goster('sec1','d1')">1</a>
         </span>
         <span class="dugme" id='d2'>
               <a href="javascript:goster('sec2','d2')">2</a>
         </span>
         <span class="dugme" id='d3'>
               <a href="javascript:goster('sec3','d3')">3</a>
         </span>
         <span class="dugme" id='d4'>
               <a href="javascript:goster('sec4','d4')">4</a>
         </span>
         <span class="dugme" id='d5'>
               <a href="javascript:goster('sec5','d5')">5</a>
         </span>
         <span class="dugme" id='d6'>
               <a href="javascript:goster('sec6','d6')">6</a>
         </span>
    </div>
    <div id="haberdetay">
         <div id="sec1" style="display: none">
<h3>CDISC Ana Prensipler</h3>
<div class="yazi">
<ul class="yazi">
    <li> Standartların geliştirilmesinde öncülük eder. Klinik araştırmalarının bilimsel doğasını geliştirir.
    <li> Sık ve düzenli beslemelerle ulaşılacak üstün hedefi anlamak gerekir. Bu bilimsel içerikte esneklik sağlar. Kolaylıkla uygulanabilir, anlaşılabilir ve kuralcı izleyiciler tarafından izlenebilir.
    <li> Standart veri modelinin veri içeriği, yapısı ve kalitesi üstün anlamlı, uygulama stratejisinden bağımsız olması kabul edilir.
    <li> CDISC için genel, disiplinler arası, değişik işlevsellik bileşimleri ve iş sınıflarını düzenler.
    <li> Başka sınıflarla birlikte çalışarak, en üst düzeyde bilgi paylaşımını ve en az güç harcamayı hedeflemek.
    <li> CDISC standartları, modelleri, değerleri ve yararları hakkındai eğitimsel programlar düzenlemek.
    <li> Satıcıları ve kurumları yüceltmeden CDISC hedefleriini ve amaçlarını yakalamak.
</ul>
Ayrıntılar için <a href="cdisc-odm.html">tıklayın</a>.
</div>
         </div>
         <div id="sec2" style="display: none">
<div class="yazi">
<h3>SDXF</h3>
"Structured Data eXchange Format" (Yapısal Veri Değişim Kalıbı)
anlamına gelir ve Internet RFC 3072 kodu ile yayımlanmıştır.
<br><br>
Değişik değişik türlerdeki verilerin değişik yapılarını değişik mimari tasarımlarıyla bilgisayarlar arası değişim için bir araya getirir.
<br><br>
Verilerinizi sıradışı yapılandırma becerisi ve onların kendini tanımlayan yapıda dizilmesi XML'i andırır. Ama SDXF XML gibi yazı kalıplaması değildir. SDXF yapısını bir yazı düzenleyicisiyle (editör) okuyup değiştiremezsiniz.
<br><br>
Ayrıntılar için <a href="sdxf.html">tıklayın</a>.
</div>
         </div>
         <div id="sec3" style="display: none">
<div class="yazi">
<h3>UN/EDIFACT</h3>
UN/EDIFACT, Birleşmiş Milletler Yönetim, Ticaret ve Taşıma için Elektronik Veri Değişimi (United Nations/Electronic Data Interchange For Administration, Commerce, and Transport) aslında Birleşmiş Milletler altında geliştirilen uluslararası Elektronik Veri Değişimidir.
Bu standartın geliştirilmesi işi Birleşmiş Milletlerin Ticaret Olanakları ve Elektronik Ticaret Merkezinde yapılır. Bu bölüm Avrupa Ekonomik Komisyonu altında çalışır.
EDIFACT ISO tarafından ISO-9735 standartı olarak alınmış ve tanımlanmıştır.
<br><br>
EDIFACT standartı şunları sağlar:
<ul class="yazi">
    <li> A set of syntax rules to structure data,
    <li> An interactive exchange protocol (I-EDI),
    <li> Standard messages which allow multi-country and multi-industry exchange.
</ul>
Ayrıntılar için <a href="edifact.html">tıklayın</a>.
</div>
         </div>
         <div id="sec4" style="display: none">
<div class="yazi">
<h3>Çevresel Veri Değişimi</h3>
Çevresel Veri Değişimi, aslında çevreyle ilgili haberleri, iş listelerini ve ihaleleri üyeleri için web sayfalarında görüntüler. 
<br><br>
Ayrıntılar için <a href="cvd.html">tıklayın</a>.
</div>
         </div>
         <div id="sec5" style="display: none">
<div class="yazi">
<h3>Veri Değişimi için JSON</h3>
JSON dil bağımsız veri değişim kalıplamasıdır. Birçok dil tarafından uygulanmıştır. JSON yapısı diziler ve nesnelerde Javascript kalıplamasına dayanır. Değişik diller arasında bilgi değişimini XML ve diğer standartların yükünü hissettirmeden çözümleyen bir yöntemdir.
<br><br>
JSON aslında javascript dil kurallarına bağımlı olduğundan, Javascript altında veri geçirmek çok kolaydır. JSON nesneleri Javascript eval() işleviyle kolayca yorumlanabilir. Bu nedenle Lasso ve Javascript'ten verileri yaratılan HTML sayfalarına ya da AJAX işlemcisine geçirmek kolay olur.
<br><br>
Ayrıntılar için <a href="json.html">tıklayın</a>.
</div>
         </div>
         <div id="sec6" style="display: none">
<div class="yazi">
<h3>Veri Değişim Kalıbı</h3>
Burada MIDAS ve diğer sistemler arasında veri değişiminin nasıl yapıldığı anlatılır. MIDAS, Esnek Görüntü Taşıma Sistemi (FITS - Flaxible Image Transport System) kalıbını, veri değişimi için resmi kalıp olarak destekler. Veriler astronomi enstütüleri arasında bilgi alışverişi için kullanılır. Burada verinin bilgisayar bağımsız tanımı yapılmıştır.
<br><br>
MIDAS resmi olarak veri değişimi için yalnız FITS kalıbını destekler. Geriye dönük uyumluluk açısından IHAP kalıbını da okuyabilir (eski ESO görüntü işleme sistemlerinde kullanılmaktaydı). Diğer kalıplar desteklenmez ve bu konuda yardım da sunulmaz.
<br><br>
Ayrıntılar için <a href="eso.html">tıklayın</a>.
</div>
         </div>
    </div>
