       <img src="resimler/bosresim.jpg" width="140" height="120" class="lpic">
       <div class="yazi">
       ba nna sbsbsbbs anana<br />
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana<br />
       ba nna sbsbsbbs anana<br />
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana<br />
       ba nna sbsbsbbs anana<br />
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana
       ba nna sbsbsbbs anana<br />
       ba nna sbsbsbbs anana<br />
       ba nna sbsbsbbs anana<br />
