       <table cellpadding="0" cellspacing="0" width="514">
       <tr><td valign="top">
                <div id="kutu">
<br />
<br />
<a href="apps/sdxf.php">SDXF</a><br />Yapısal Veri Değişimi<br />
Web uygulaması
                </div>
            </td>
            <td valign="top">
                <div id="kutu">
<br />
<br />
<a href="apps/cdisc.php">CDISC</a><br />Klinik Veri Değişimi<br />
Web uygulaması
                </div>
            </td>
            <td valign="top">
                <div id="kutu">
<br />
<br />
<a href="apps/cvd.php">CVD</a><br />Çevresel Veri Değişimi<br />
                </div>
            </td></tr>
       <tr><td valign="top">
                <div id="kutu">
<br />
<br />
<a href="apps/edifact.php">EDIFACT</a><br />UN/EDIFACT Veri Değişimi<br />
Web uygulaması
                </div>
            </td>
            <td valign="top">
                <div id="kutu">
<br />
<br />
<a href="apps/midas.php">MIDAS/FITS</a><br />MIDAS/FITS Veri Değişimi<br />
Web uygulaması
                </div>
            </td>
            <td valign="top">
                <div id="kutu">
<br>
<br>
<a href="apps/zvd.php">ZVD</a><br />Tarımsal Veri Değişimi<br />
Çok yeni bir uygulama...
                </div>
            </td></tr>
       </table>
