  <div id="soltaraf">
    <center><div id="yazi"><h3>Veri Değişimi</h3></div></center>
    <div id="masterdiv">
        <div class="menutitle" onclick="SwitchMenu('sub1')">Ugulamalar</div>
        <span class="submenu" id="sub1">
                - <a href="apps/sdxf.php">SDXF</a><br>
                - <a href="apps/cdisc.php">CDISC</a><br>
                - <a href="apps/cvd.php">CVD</a><br>
                - <a href="apps/zvd.php">ZVD</a><br>
                - <a href="apps/edifact.php">EDIFACT</a><br>
                - <a href="apps/midas.php">MIDAS/FITS</a><br>
                - <a href="apps/json.php">JSON</a><br>
        </span>
        <div class="menutitle" onclick="SwitchMenu('sub2')">Çeşitli Belgeleri</div>
        <span class="submenu" id="sub2">
                - <a href="cdisc-odm1.html">CDISC-1</a><br>
                - <a href="cdisc-odm2.html">CDISC-2</a><br>
                - <a href="sdxf.html">RFC 3072</a><br>
                - <a href="edifact.html">UN/EDIFACT</a><br>
                - <a href="cvd.html">CVD Belgeleri</a><br>
                - <a href="zvd.html">ZVD Belgeleri</a><br>
                - <a href="json.html">Veri Değişmi için JSON</a><br>
                - <a href="eso.html">MIDAS/FITS Kalıbı</a><br>
        </span>
        <div class="menutitle">
             <a href="apps/index.php" class="vnav">Üye Olun</a>
        </div>
    </div>
  </div>
