    <div id="haber">
         <span class="dugme" id='d0'>
               Güncel Haberler
         </span>
         <span class="dugme" id='d1'>
               <a href="javascript:goster('sec1','d1')">1</a>
         </span>
         <span class="dugme" id='d2'>
               <a href="javascript:goster('sec2','d2')">2</a>
         </span>
         <span class="dugme" id='d3'>
               <a href="javascript:goster('sec3','d3')">3</a>
         </span>
    </div>
    <div id="haberdetay">
         <div id="sec1" style="display: none">
             haber 1&nbsp;&nbsp; haber 1&nbsp;&nbsp; haber 1&nbsp;&nbsp;
             haber 1&nbsp;&nbsp; haber 1&nbsp;&nbsp; haber 1&nbsp;&nbsp;
             haber 1&nbsp;&nbsp; haber 1
         </div>
         <div id="sec2" style="display: none">
             haber 2&nbsp;&nbsp; haber 2&nbsp;&nbsp; haber 2&nbsp;&nbsp;
             haber 2&nbsp;&nbsp; haber 2&nbsp;&nbsp; haber 2&nbsp;&nbsp;
             haber 2&nbsp;&nbsp; haber 2&nbsp;&nbsp; haber 2&nbsp;&nbsp;
             haber 2&nbsp;&nbsp; haber 2&nbsp;&nbsp; haber 2&nbsp;&nbsp;
             haber 2&nbsp;&nbsp; haber 2
         </div>
         <div id="sec3" style="display: none">
             haber 3&nbsp;&nbsp; haber 3&nbsp;&nbsp; haber 3&nbsp;&nbsp;
             haber 3&nbsp;&nbsp; haber 3&nbsp;&nbsp; haber 3&nbsp;&nbsp;
             haber 3&nbsp;&nbsp; haber 3&nbsp;&nbsp; haber 3&nbsp;&nbsp;
             haber 3&nbsp;&nbsp; haber 3
         </div>
    </div>
