       <div class="borderright">
         bu bir ornek satir
         bu bir ornek satir<br />
         bu bir ornek satir
         bu bir ornek satir<br />
         bu bir ornek satir<br />
         bu bir ornek satir<br />
         <br />
         <form>
           <div id="sifre" class="yazi">
            <table class="yazi">
               <tr><th colspan="2"><center>ÜYE GİRİŞİ</center></th></tr>
              <tr><td valign="top">Üye No</td>
                  <td valign="top"><input type="text" name="user" size="8" class="required"></td></tr>
              <tr><td valign="top">Şifre</td>
                      <td valign="top"><input type="text" name="passwd" size="8" class="required">
                    <input type="button" onclick="javascirpt:" value="Git"></td></tr>
            </table>
           </div>
         </form>
         <br />
         bu bir ornek satir
         bu bir ornek satir
         bu bir ornek satir
         bu bir ornek satir<br />
       </div>
